SystemJAADE/healthy-patients-service

.github/wiki/1.-Estilo-de-codigo.md
.github/wiki/2.-Leer-antes-de-instalar.md
.github/wiki/3.-Instalacion-con-docker.md
.github/wiki/4.-Instalacion-manual.md
.github/wiki/Home.md
.github/workflows/docs.yml

docs: Move all documentation to wikis

---

docker-compose.yml

chore: Set dockerfile default target as dev

---

docker-compose.yml

fix: Fix docker not launching due to a bug with prisma

---

prisma/schema.prisma
src/app.module.ts
src/triages/dto/triage.dto.ts
src/triages/triages.controller.ts
src/triages/triages.module.ts
src/triages/triages.repository.ts
src/triages/triages.service.ts

feat: Implement triages module

---

.env.example
docker-compose.yml
ext/init_shadow_db.sql
prisma/schema.prisma

fix: Add support for shadow db (Prisma) in docker

---

src/accounts/accounts.controller.ts
src/credentials/credentials.controller.ts
src/main.ts
src/oauth/oauth.middleware.ts
src/triages/triages.controller.ts

feat: Add Bearer authentication to OpenAPI

---

src/helpers/role.helper.ts
src/triages/triages.controller.ts

refactor: Allow multiple roles to endpoints

---

.github/wiki/2.-Leer-antes-de-instalar.md
.github/wiki/4.-Instalacion-manual-linux.md
.github/wiki/5.-Instalacion-manual-windows.md

Closes #28 
- Add windows manual installation

docs: Improve documentation

---

.env.example
.github/wiki/5.-Instalacion-manual-windows.md

Also the documentation has been updated to reflect the changes

chore: remove SHADOW_DB_PASS env and simplify shadow db configuration

---

prisma/schema.prisma

chore: Add missing binaryTargets to schema.prisma

---

.github/wiki/5.-Instalacion-manual-windows.md

add comand: npx prisma generate

docs: Add documentation about prisma generate

---

.github/wiki/6.-Reverse-proxy.md
Makefile
ext/Caddyfile

chore: Add Caddyfile

---

docker-compose.yml

chore: Add host and port in mysql healthcheck

---

.github/workflows/sync_docs.yml

chore: Fix wiki bi-directional sync

---

prisma/schema.prisma

The database already in place is part of the rewrite to the database, ~~this PR will cover all the tables that have yet to be migrated from the old database.~~
Edit: Because there are a lot of tables and we want to move forward with the API implementation, this will be done in different PRs.
New tables:
- daily_attendance_records
- icd10_categories
- icd10_chapters
- icd10_groups
- icd10_diagnoses
- specialties
- ubigeo_departments
- ubigeo_provinces
- ubigeo_districts

chore: Adding some of the missing tables to the database

---

src/app.module.ts
src/main.ts

chore: Add link to postman collection JSON

---

prisma/schema.prisma
src/accounts/accounts.controller.ts
src/accounts/accounts.module.ts
src/accounts/accounts.repository.ts
src/credentials/credentials.controller.ts
src/credentials/credentials.module.ts
src/credentials/credentials.repository.ts
src/helpers/validate.helper.ts
src/oauth/oauth.controller.ts
src/oauth/oauth.middleware.ts
src/oauth/oauth.module.ts
src/oauth/oauth.service.ts
src/triages/triages.controller.spec.ts
src/triages/triages.controller.ts
src/triages/triages.module.ts
src/triages/triages.repository.ts
src/triages/triages.service.spec.ts
test/app.e2e-spec.ts

test: Add unit tests for triages

---

.env.example
src/main.ts

feat: Enable CORS with env origins

---

openapi.json
src/accounts/accounts.controller.ts
src/accounts/dto/account.dto.ts
src/app.module.ts
src/credentials/credentials.controller.ts
src/main.ts
src/oauth/dto/change-password.dto.ts
src/oauth/dto/registration.dto.ts
src/oauth/dto/sign-in-response.dto.ts
src/oauth/dto/sign-in.dto.ts
src/oauth/oauth.controller.ts
src/swagger/swagger.config.ts
src/triages/dto/triage.dto.ts
src/triages/triages.controller.ts

Some endpoints are still missing in the documentation i think

feat: Use openapi.json to generate documentation instead of using annotations

---

.env.example
package.json
src/accounts/accounts.controller.ts
src/accounts/accounts.module.ts
src/accounts/accounts.service.ts
src/accounts/dto/buffered-image.dto.ts
src/app.module.ts
yarn.lock

Depends on [this](https://github.com/SystemJAADE/healthy-assets-service/)
TODO:
- Add the new endpoint to the documentation (OpenAPI/Swagger)

feat: Add endpoints to get and upload accounts avatars

---

src/app.module.ts
src/ubigeo/ubigeo.controller.ts
src/ubigeo/ubigeo.module.ts
src/ubigeo/ubigeo.repository.ts
src/ubigeo/ubigeo.service.ts

feat: Add ubigeo module

---

.env.example
bin/start-dev.sh

- Also Fix SHADOW_DB_URL having wrong user

Sync database when starting the app from docker
